name: Run unittest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-compose.test.yaml
      DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_PASS: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      run: docker login -u $DOCKER_USER -p $DOCKER_PASS

    - name: Run tests
      run: docker-compose -f $COMPOSE_FILE up --build --exit-code-from flask_app_test
