steps:
  # Docker Build
  - name: "gcr.io/cloud-builders/docker"
    args: [
      "build",
      "--target", "production",
      "-t", "gcr.io/${PROJECT_ID}/belinsky:${SHORT_SHA}",
      "app/."
    ]

  # Docker push to GCR.io
  - name: "gcr.io/cloud-builders/docker"
    args: ["push",  "gcr.io/${PROJECT_ID}/belinsky:${SHORT_SHA}"]

images:
  - gcr.io/${PROJECT_ID}/belinsky:${SHORT_SHA}
