steps:
  # Install dependencies.
  - name: python
    entrypoint: pip
    args: [ "install", "-r", "app/requirements.txt", "--user" ]

  # Run tests
  - name: python
    entrypoint: pip
    args: [ "install", "pytest==7.1.1", "blinker==1.4", "--user" ]

  # Docker Build
  - name: "gcr.io/cloud-builders/docker"
    args: [
      "build",
      "--target", "production",
      "-t", "gcr.io/${PROJECT_ID}/belinsky:${SHORT_SHA}",
      "app/."
    ]

  # Docker push to GCR.io
  - name: "gcr.io/cloud-builders/docker"
    args: ["push",  "gcr.io/${PROJECT_ID}/belinsky:${SHORT_SHA}"]

images:
  - gcr.io/${PROJECT_ID}/belinsky:${SHORT_SHA}
