services:
  app_test:
    build:
      context: app/
      target: test
    command: python app_test.py
    restart: "no"

    environment:
      MONGODB_USERNAME: admin
      MONGODB_PASSWORD: admin_password
      MONGODB_HOSTNAME: belinsky_database_test

    depends_on:
      - database_test

  database_test:
    image: mongo
    command: mongod --quiet --logpath /dev/null
    container_name: belinsky_database_test
    restart: unless-stopped

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin_password
      MONGO_INITDB_DATABASE: belinsky_db
      MONGODB_DATA_DIR: /data/db

    volumes:
      - mongodbdata_test:/data/db

volumes:
  mongodbdata_test:
    driver: local