services:
  prometheus:
    image: prom/prometheus

    ports:
      - "9090:9090"
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml

networks:
  default:
    external:
      name: belinsky_network