services:
  flask_app_test:
    build:
      context: .
      target: test
    container_name: flask_app_test
    environment:
      MONGODB_DATABASE: flaskdb
      MONGODB_USERNAME: admin
      MONGODB_PASSWORD: admin_password
      MONGODB_HOSTNAME: mongodb

    depends_on:
      - mongodb_test

  mongodb_test:
    image: mongo
    command: mongod --quiet --logpath /dev/null
    container_name: mongodb_test
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin_password
      MONGO_INITDB_DATABASE: flaskdb
      MONGODB_DATA_DIR: /data/db
    volumes:
      - mongodbdata_test:/data/db

volumes:
  mongodbdata_test:
    driver: local