services:
  app:
    build:
      context: app/
      target: production
    command: gunicorn wsgi:app --config "${BELINSKY_GUNICORN_CONFIG-gunicorn_config.py}"
    container_name: belinsky_app
    restart: unless-stopped

    environment:
      BELINSKY_POSTGRES_USER: belinsky
      BELINSKY_POSTGRES_PASSWORD: belinsky_db_password
      BELINSKY_POSTGRES_HOST: belinsky_database
      BELINSKY_POSTGRES_PORT: 5432
      BELINSKY_POSTGRES_DB: belinsky_db

    ports:
      - "${BELINSKY_PORT-4958}:5000"

    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres
    container_name: belinsky_database
    restart: unless-stopped

    environment:
      POSTGRES_USER: belinsky
      POSTGRES_PASSWORD: belinsky_db_password
      POSTGRES_DB: belinsky_db

    volumes:
      - belinsky_db_volume:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U belinsky -d belinsky_db -q"]
      interval: 2s
      timeout: 2s
      retries: 10

volumes:
  belinsky_db_volume:
    driver: local

networks:
  default:
    name: belinsky_network
    driver: bridge