services:
  app:
    build:
      context: app/
      target: production
    command: sh start_gunicorn.sh
    container_name: belinsky_app
    restart: unless-stopped

    environment:
      MONGODB_USERNAME: admin
      MONGODB_PASSWORD: admin_password
      MONGODB_HOSTNAME: belinsky_database

    ports:
      - "${BELINSKY_PORT-4958}:5000"
    depends_on:
      - database

  database:
    image: mongo
    command: mongod --quiet --logpath /dev/null
    container_name: belinsky_database
    restart: unless-stopped

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin_password
      MONGO_INITDB_DATABASE: belinsky_db
      MONGODB_DATA_DIR: /data/db

    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata:
    driver: local

networks:
  default:
    name: belinsky_network
    driver: bridge