services:
  word_finder_app_test:
    build:
      context: word_finder_app/
      target: test
    command: python test.py
    container_name: word_finder_app_test
    restart: "no"

    environment:
      MONGODB_USERNAME: admin
      MONGODB_PASSWORD: admin_password
      MONGODB_HOSTNAME: word_finder_db_test

    depends_on:
      - word_finder_db_test

  word_finder_db_test:
    image: mongo
    command: mongod --quiet --logpath /dev/null
    container_name: word_finder_db_test
    restart: unless-stopped

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin_password
      MONGO_INITDB_DATABASE: word_finder_db
      MONGODB_DATA_DIR: /data/db

    volumes:
      - mongodbdata_test:/data/db

volumes:
  mongodbdata_test:
    driver: local