services:
  prometheus:
    image: prom/prometheus

    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana

    ports:
      - "${BELINSKY_OBSERVABILITY_PORT-4800}:3000"

networks:
  default:
    external:
      name: belinsky_network