services:
  nginx:
    build: nginx/
    container_name: word_finder_nginx

    ports:
      - "4958:80"
    depends_on:
      - app
      - app_backup

  app:
    build:
      context: word_finder_app/
      target: production
    command: gunicorn main:"create_app()" -b 0.0.0.0:5000
    restart: unless-stopped

    environment:
      MONGODB_USERNAME: admin
      MONGODB_PASSWORD: admin_password
      MONGODB_HOSTNAME: word_finder_database

    expose:
      - "5000"
    depends_on:
      - database

  app_backup:
    build:
      context: word_finder_app/
      target: production
    command: gunicorn main:"create_app()" -b 0.0.0.0:4999
    restart: unless-stopped

    environment:
      MONGODB_USERNAME: admin
      MONGODB_PASSWORD: admin_password
      MONGODB_HOSTNAME: word_finder_database

    expose:
      - "4999"
    depends_on:
      - database

  database:
    image: mongo
    command: mongod --quiet --logpath /dev/null
    container_name: word_finder_database
    restart: unless-stopped

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin_password
      MONGO_INITDB_DATABASE: word_finder_db
      MONGODB_DATA_DIR: /data/db

    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata:
    driver: local
