services:
  app_test:
    build:
      context: app/
      target: test
    command: pytest -W ignore::DeprecationWarning
    restart: "no"

    environment:
      BELINSKY_SECRET_KEY: ${BELINSKY_SECRET_KEY}
      BELINSKY_GOOGLE_CLOUD_API_KEY: ${BELINSKY_GOOGLE_CLOUD_API_KEY}

      BELINSKY_POSTGRES_USER: belinsky
      BELINSKY_POSTGRES_PASSWORD: belinsky_db_password
      BELINSKY_POSTGRES_HOST: belinsky_database_test
      BELINSKY_POSTGRES_PORT: 5432
      BELINSKY_POSTGRES_DB: belinsky_db

    depends_on:
      database_test:
        condition: service_healthy

  database_test:
    image: postgres
    container_name: belinsky_database_test
    restart: unless-stopped

    environment:
      POSTGRES_USER: belinsky
      POSTGRES_PASSWORD: belinsky_db_password
      POSTGRES_DB: belinsky_db

    ports:
      - "5432:5432"

    volumes:
      - belinsky_db_test_volume:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U belinsky -d belinsky_db -q"]
      interval: 2s
      timeout: 2s
      retries: 10

volumes:
  belinsky_db_test_volume:
    driver: local