services:
  nginx:
    build: nginx/
    container_name: belinsky_nginx

    ports:
      - "4958:4958"
    depends_on:
      - app
      - app_backup

  app:
    build:
      context: app/
      target: production
    command: gunicorn app:"create_app()" -b 0.0.0.0:5000 -w 4
    restart: unless-stopped

    environment:
      MONGODB_USERNAME: admin
      MONGODB_PASSWORD: admin_password
      MONGODB_HOSTNAME: belinsky_database

    expose:
      - "5000"
    depends_on:
      - database

  app_backup:
    build:
      context: app/
      target: production
    command: gunicorn app:"create_app()" -b 0.0.0.0:4999  -w 4
    restart: unless-stopped

    environment:
      MONGODB_USERNAME: admin
      MONGODB_PASSWORD: admin_password
      MONGODB_HOSTNAME: belinsky_database

    expose:
      - "4999"
    depends_on:
      - database

  database:
    image: mongo
    command: mongod --quiet --logpath /dev/null
    container_name: belinsky_database
    restart: unless-stopped

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin_password
      MONGO_INITDB_DATABASE: belinsky_db
      MONGODB_DATA_DIR: /data/db

    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata:
    driver: local
