services:
  flask:
    build: .
    container_name: flask
    restart: unless-stopped
    environment:
      MONGODB_DATABASE: flaskdb
      MONGODB_USERNAME: user
      MONGODB_PASSWORD: user_password
      MONGODB_HOSTNAME: mongodb

    depends_on:
      - mongodb
    ports:
      - "4958:5000"

  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin_password
      MONGO_INITDB_DATABASE: flaskdb
      MONGODB_DATA_DIR: /data/db
    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata:
    driver: local