services:
  prometheus:
    image: prom/prometheus

    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana

    ports:
      - "${BELINSKY_OBSERVABILITY_PORT-4800}:3000"
    volumes:
      - ./observability/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./observability/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./observability/main-dashboard.json:/etc/grafana/provisioning/dashboards/main-dashboard.json

networks:
  default:
    external:
      name: belinsky_network