global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']

  - job_name: 'belinsky_app'
    metrics_path: '/metrics/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['app:5000']
