name: Tests

on:
  push:
    branches: [master, dev/stage]
  pull_request:
    branches: [master, dev/stage]

jobs:
  run_tests:
    name: Run Tests
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-compose.test.yaml

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Run Tests
        run: docker-compose -f $COMPOSE_FILE up --build --abort-on-container-exit
